name: Run Tests
on:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: filter
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  test:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services ) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: services/node/api-node/package.json
          cache: "npm"
          cache-dependency-path: services/node/api-node/package-lock.json

      - name: Setup Go environment
        if: ${{ startsWith(matrix.service, 'services/go/' )}}
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum
      
      - name: Setup Poetry
        if: ${{ startsWith(matrix.service, 'services/python')}}
        uses: snok/install-poetry@v1.4.2

      - name: Setup Python
        if: ${{ startsWith(matrix.service, 'services/python')}}
        uses: actions/setup-python@v5.6.0
        with:
            cache: poetry
            cache-dependency-path: ${{ matrix.service }}/poetry.lock
            python-version-file: ${{ matrix.service }}/pyproject.toml

      
      - name: Install Task
        uses: supplypike/setup-bin@v4.0.1
        with: 
          uri: "https://github.com/go-task/task/releases/download/v3.53.1/task_linux_amd64.tar.gz"
          name: task
          version: v3.53.1
      
      - name: Install Apps Deps
        working-directory: ${{ matrix.service }}
        run : |
          task install-ci
      
      - name: Install Tests
        working-directory: ${{ matrix.service }}
        run : |
          task test

  